/**
 * chat_api — WebSocket client (generated by wsforge)
 * Protocol: request/response envelopes with id correlation + server pushes.
 * Transport: ws://localhost:8080/ws  (ws and wss supported)
 */
const isNode = typeof process !== 'undefined' && !!process.versions?.node;

let NativeWebSocket = globalThis.WebSocket;
async function wsImpl() {
  if (NativeWebSocket) return NativeWebSocket;
  // Node.js: use the `ws` package
  const m = await import('ws');
  return m.default ?? m.WebSocket;
}

export class WsClient {
  /**
   * @param {string} [url="ws://localhost:8080/ws"]
   * @param {object} [opts]
   * @param {string} [opts.token] JWT for authenticated servers
   * @param {number} [opts.requestTimeoutMs=15000]
   * @param {boolean} [opts.autoReconnect=true]
   */
  constructor(url = "ws://localhost:8080/ws", opts = {}) {
    this.url = url;
    this.opts = opts;
    this.ws = null;
    this.seq = 0;
    this.pending = new Map();   // id -> {resolve, reject, timer}
    this.listeners = new Map(); // type -> Set<fn>
    this.connected = false;
  }

  /** Connect (and authenticate, if a token was provided). */
  async connect() {
    const Impl = await wsImpl();
    const sep = this.url.includes('?') ? '&' : '?';
    const url = this.opts.token ? `${this.url}${sep}token=${encodeURIComponent(this.opts.token)}` : this.url;
    await new Promise((resolve, reject) => {
      this.ws = new Impl(url);
      this.ws.onopen = () => { this.connected = true; resolve(); };
      this.ws.onerror = (e) => reject(new Error('websocket error'));
      this.ws.onclose = () => this.#onClose();
      this.ws.onmessage = (ev) => this.#onMessage(ev.data);
    });
    return this;
  }

  close() { this.ws?.close(); }

  /** Low-level request/response with timeout. */
  request(type, payload) {
    if (!this.connected) return Promise.reject(new Error('not connected'));
    const id = `r${++this.seq}`;
    return new Promise((resolve, reject) => {
      const timeout = this.opts.requestTimeoutMs ?? 15000;
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(`timeout waiting for ${type}.ok`));
      }, timeout);
      this.pending.set(id, { resolve, reject, timer });
      this.ws.send(JSON.stringify({ id, type, payload }));
    });
  }

  /** Subscribe to server messages of a given type. Returns unsubscribe fn. */
  on(type, fn) {
    if (!this.listeners.has(type)) this.listeners.set(type, new Set());
    this.listeners.get(type).add(fn);
    return () => this.listeners.get(type)?.delete(fn);
  }

  #onMessage(data) {
    let msg;
    try { msg = JSON.parse(data); } catch { return; }
    const { id, type, payload } = msg;
    if (id && this.pending.has(id)) {
      const p = this.pending.get(id);
      this.pending.delete(id);
      clearTimeout(p.timer);
      if (type.endsWith('.error')) p.reject(Object.assign(new Error(payload?.message ?? 'error'), { code: payload?.code }));
      else p.resolve(payload);
      return;
    }
    for (const fn of this.listeners.get(type) ?? []) fn(payload, msg);
    for (const fn of this.listeners.get('*') ?? []) fn(msg);
  }

  #onClose() {
    this.connected = false;
    for (const [id, p] of this.pending) {
      clearTimeout(p.timer);
      p.reject(new Error('connection closed'));
      this.pending.delete(id);
    }
    if (this.opts.autoReconnect !== false) {
      setTimeout(() => this.connect().catch(() => {}), 1000);
    }
  }

  /** `messages.create` */
  messagesCreate(payload) { return this.request('messages.create', payload); }

  /** `messages.delete` */
  messagesDelete(payload) { return this.request('messages.delete', payload); }

  /** `messages.get` */
  messagesGet(payload) { return this.request('messages.get', payload); }

  /** `messages.list` */
  messagesList(payload) { return this.request('messages.list', payload); }

  /** `messages.update` */
  messagesUpdate(payload) { return this.request('messages.update', payload); }

  /** `rooms.create` */
  roomsCreate(payload) { return this.request('rooms.create', payload); }

  /** `rooms.delete` */
  roomsDelete(payload) { return this.request('rooms.delete', payload); }

  /** `rooms.get` */
  roomsGet(payload) { return this.request('rooms.get', payload); }

  /** `rooms.list` */
  roomsList(payload) { return this.request('rooms.list', payload); }

  /** `rooms.update` */
  roomsUpdate(payload) { return this.request('rooms.update', payload); }

  /** `users.create` */
  usersCreate(payload) { return this.request('users.create', payload); }

  /** `users.delete` */
  usersDelete(payload) { return this.request('users.delete', payload); }

  /** `users.get` */
  usersGet(payload) { return this.request('users.get', payload); }

  /** `users.list` */
  usersList(payload) { return this.request('users.list', payload); }

  /** `users.update` */
  usersUpdate(payload) { return this.request('users.update', payload); }

  /** Join a room (pub/sub channel). */
  joinRoom(room) { return this.request('room.join', { room }); }
  /** Leave a room. */
  leaveRoom(room) { return this.request('room.leave', { room }); }
  /** Send data to a room; listen with `on('room.message', fn)`. */
  sendRoom(room, data) { return this.request('room.message', { room, data }); }

  /** Obtain a token for `subject` (dev/login gateway). */
  authToken(subject) { return this.request('auth.token', { subject }); }
}

export default WsClient;
void isNode;
