-- Generated by wsforge (database: postgres)
CREATE SCHEMA IF NOT EXISTS auth;
CREATE TYPE message_status AS ENUM ('sent', 'delivered', 'read');

CREATE TABLE IF NOT EXISTS auth.users (	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),	username TEXT NOT NULL UNIQUE,	email TEXT NOT NULL UNIQUE,	status BOOLEAN,	online BOOLEAN,	last_seen TIMESTAMPTZ,	created_at TIMESTAMPTZ NOT NULL,	updated_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS auth.rooms (	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS messages (	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	room_id INTEGER NOT NULL,	author_id UUID NOT NULL,	body TEXT NOT NULL,	status message_status,	created_at TIMESTAMPTZ NOT NULL,	updated_at TIMESTAMPTZ);
ALTER TABLE messages ADD CONSTRAINT fk_messages_room_id
	FOREIGN KEY (room_id) REFERENCES auth.rooms (id);
ALTER TABLE messages ADD CONSTRAINT fk_messages_author_id
	FOREIGN KEY (author_id) REFERENCES auth.users (id);
