-- Generated by wsforge (database: sqlite)

CREATE TABLE IF NOT EXISTS users (	id TEXT PRIMARY KEY,	username TEXT NOT NULL UNIQUE,	email TEXT NOT NULL UNIQUE,	status TEXT,	created_at TEXT NOT NULL,	updated_at TEXT);
CREATE TABLE IF NOT EXISTS rooms (	id INTEGER PRIMARY KEY AUTOINCREMENT,	name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS messages (	id INTEGER PRIMARY KEY AUTOINCREMENT,	room_id INTEGER NOT NULL,	author_id TEXT NOT NULL,	body TEXT NOT NULL,	status TEXT,	created_at TEXT NOT NULL,	updated_at TEXT);
-- FK: messages.room_id -> auth.rooms (id[)
-- FK: messages.author_id -> auth.users (id)
